### ISSUE TITLE
index file smaller than expected

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/access-om2#223]
Since yesterday, I am not able to run ACCESS-OM2, with this error (1deg_jra55_iaf.e13212477):

Currently Loaded Modulefiles:
 1) pbs   2) openmpi/4.0.2(default)
fatal: index file smaller than expected
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/bin/payu-run", line 10, in <module>
    sys.exit(runscript())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/subcommands/run_cmd.py", line 132, in runscript
    expt.run()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/experiment.py", line 598, in run
    self.runlog.commit()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/runlog.py", line 89, in commit
    cwd=self.expt.control_path)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'add', '/scratch/v45/hh0162/access-om2/control/1deg_jra55_iaf_omip2/config.yaml']' returned non-zero exit status 128.

Any idea, anyone?

**Comment by aidanheerdegen** [comment]
Where is your control directory @hakaseh?

**Comment by aidanheerdegen** [comment]
Your `git` repository has become corrupted. This usually occurs when a `git` operation is interrupted by something like a computer or disk crash.

You can try the solution suggested here:

https://stackoverflow.com/a/14594665

But I have never had to deal with this so I can't say I have ever done this.

**Comment by hakaseh** [comment]
Thanks @aidanheerdegen for finding this solution. After many days of hibernation, I finally got to work on this issue this morning, and resolved it right away after trying the method above. 

In my case, I had to delete .git, git clone to obtain a new .git, and place it to the directory where I deleted .git.
