### ISSUE TITLE
OverflowError: date value out of range

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/access-om2#228]
Hi @aidanheerdegen this error might be related to Payu.

My run is at Year 2501, which does not start due to the following error:

vi /scratch/v45/hh0162/access-om2/control/1deg_jra55_iaf_omip2r1i2p2f1.e14870883

Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/bin/payu-run", line 10, in <module>
    sys.exit(runscript())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/subcommands/run_cmd.py", line 131, in runscript
    expt.setup()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/experiment.py", line 422, in setup
    model.setup()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/models/cice5.py", line 56, in setup
    super(Cice5, self).setup()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/models/cice.py", line 217, in setup
    caltype)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/payu/calendar.py", line 51, in date_plus_seconds
    end_date += get_leapdays(init_date, end_date)
OverflowError: date value out of range

Any idea why this happens? My latest successful output and restart files are labeled 2499 (output2499 and restart2499).

**Comment by aekiss** [comment]
@hakaseh is this still a problem?

**Comment by hakaseh** [comment]
yes, i haven't done anything since then.

**Comment by aekiss** [comment]
since this looks like a payu problem, it should probably be reposted to https://github.com/payu-org/payu/issues

**Comment by hakaseh** [comment]
ok will try to do.

**Comment by hakaseh** [comment]
i closed and reposted to https://github.com/payu-org/payu/issues/303
